server:
  port: 8005 #Puerto por defecto para temas de apigateway

spring:
  sql:
    init-mode: always
  jpa:
    database: MYSQL
    show-sql: true
  datasource:
    platform: mysql
    url: jdbc:mysql://localhost:3306/${spring.datasource.database}
    initialization-mode: always
    driver-class-name: com.mysql.cj.jdbc.Driver