---
server:
  port: 8085

data:
  clientId: client
  secret: secret
  passwd: password
  refresh: refresh_token
  allowed: read

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring
    username: root
    password: springbankRootPsw
    initialization-mode: always